### PR TITLE
feat : Added the PR and date fields in notion

### PR DESCRIPTION
**Pull request by amanbairagi30**
This PR adds the two new field i.e PR and Date to the notion and fixes the issue #5 

You can see the changes here @hkirat 

https://github.com/code100x/bounty-hook/assets/118182376/96ba9f7d-e41a-4a0b-af29-c1ccd4267899

### CODE REVIEW

**Comment by hkirat** [comment]
/bounty $20 -- please ping rookie, this repo isn't yet linked to bounty bot

**Comment by amanbairagi30** [comment]
> /bounty $20 -- please ping rookie, this repo isn't yet linked to bounty bot

Okay , I will ping him .

**Pull request merged**
