### PR TITLE
feat: integrated twitter to webhooks

### PR DESCRIPTION
**Pull request by shrutsureja**
- implemented the oauth2 to verify the user and make a tweet
- added a custom class `twitterClient` which handles this the auth and tweet process
- added a custom store `twitterStore` which stores all the necessary variables instead of  a database 
- added new route `GET /twitter-setup` to setup the twitter
- added new route `GET /twitter-callback` to handle the callback for oauth2

### CODE REVIEW

**Comment by shrutsureja** [comment]
adding the video of how to use it with the updated readme

**Comment by shrutsureja** [comment]
Sorry to say but this has some issue when deployed on the cloudflare worker the issue is it let the twitter authenticate and save all the necessary variable in the memory
image
But when i write /bounty and generate the webhook cycle then the same values are becoming null 
image

everything is working fine locally with ngrok i have tested that i am working on the issue

**Comment by devsargam** [comment]
Doesn't look that good with oauth and stuff

**Comment by shrutsureja** [comment]
Break down of the Twitter Part

**Main Purpose** > when Admins(users whose user names are in enviroment variables of bounty hook) of Repo type `/bounty $12` then it should make a **Tweet a Post**.

- For Tweeting the Post on Twitter their are 2 endpoints [Link Official Doc](https://developer.twitter.com/en/docs/twitter-api/tweets/manage-tweets/migrate)

This are just 2 different endpoints so with different oauth, 
- OAuth 1.0a User Context 
- OAuth 2.0 Authorization Code with PKCE

> Point to keep in mind we have to implement it using REST APIs because most packages are not working cloudflare due to node api's not being present 

Here are the resources for both the oauth methods

### OAuth 2.0 Authorization Code with PKCE

Already implemented this. But the only issue is with **storing the token in run-time** because we dont have a **DB**.

- [twitter-api-v2 npm package](https://github.com/PLhery/node-twitter-api-v2/blob/master/src/client/readonly.ts)
- [oauth2 flow and process](https://developer.twitter.com/en/docs/authentication/oauth-2-0/authorization-code)
- [oauth2 urls for authentication](https://developer.twitter.com/en/docs/authentication/oauth-2-0/user-access-token)

### Oauth 1.0a User Context

Not Impleamented but this is almost has the same method as oauth2. Maybe little bit simpler but is an older version.

- [Official Doc](https://developer.twitter.com/en/docs/authentication/oauth-1-0a)
- [Tutorial (old one)](https://developer.twitter.com/en/docs/tutorials/authenticating-with-twitter-api-for-enterprise/oauth1-0a-and-user-access-tokens)


### Issue 

Only issue is to store the token somewhere

### Solution

1. Maybe i over modularized this and i will try to make this as simple as possible.
2. Use a DB instead which can make things very easy.


Working on making a simpler version of this.

**Comment by shrutsureja** [comment]
I forgot the point that this is cloudflare which is serverless so all the runtime values will get lost eventually so their is no use of doing this twitterStore class in the run time. and this is the reason that the code is working locally and not on cloudflare workers. I think DB is the only option left to store token in both Oauth 1.0a and Oauth 2.0 we will have to save the access token somewhere
@hkirat can please review this once. If we are going to use DB, then what is the setup that i should do Prisma + Postgress or any other ?

**Comment by shrutsureja** [comment]
I have another working version will make a PR on soon

**Pull request closed without merging**
